routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Without namespace but middleware
Route::group(['middleware' => 'auth'], function(){
	Route::get('/login/{m01_user}', 'VerificationController@showVerifyForm')->name('user.verify.login.form');
	Route::post('/verify/login/{m01_user}', 'VerificationController@verifyGoogle2F')->name('user.verify.login.google2f');
	Route::get('/verify/email/{m01_user}', 'VerificationController@showVerifyEmail')->name('user.verify.login.email');
	Route::post('/verify/email/{m01_user}', 'VerificationController@verify')->name('user.verify.login.email.code');
	
});
//With namespace Frontend
Route::group(['namespace' => 'Frontend'], function(){
	Route::get('/', 'HomepageController@index')->name('user.homepages.index');
	Route::get('/home', 'HomepageController@showIndex')->name('user.homepages.showIndex');
	Route::get('/outlet-details/{m02_outlet}', 'HomepageController@outletDetail')->name('outlet.homepages.detail');
	Route::post('/contact-us/{m02_outlet}', 'HomepageController@saveMessageToOutlet')->name('user.contact-us.save.detail');
	Route::post('/feedback/{m02_outlet}', 'HomepageController@saveFeedbackToOutlet')->name('user.feedback.save.detail');
	Route::get('/news-and-events','HomepageController@newsAndEvents')->name('user.news.index');
	Route::get('/news-and-events/detail/{m03_news}','HomepageController@newsAndEventsDetail')->name('user.news.detail');
	Route::get('/terms-and-conditions', 'HomepageController@terms')->name('user.terms.index');
	Route::get('/about-us', 'HomepageController@abouts')->name('user.abouts.index');
	Route::get('/how-to-transaction', 'HomepageController@howTo')->name('user.how-to-transaction.index');
	Route::get('/delivery', 'HomepageController@delivery')->name('user.delivery.index');
	Route::post('/delivery', 'HomepageController@checkDelivery')->name('user.delivery.check');
	Route::get('/feedback', 'HomepageController@feedback')->name('user.feedback.index');
	Route::post('/feedback/save', 'HomepageController@saveFeedback')->name('user.feedback.save');
	Route::get('/contact-us', 'HomepageController@contactUs')->name('user.contact-us.index');
	Route::post('/contact-us', 'HomepageController@saveMessage')->name('user.contact-us.save');

	//Product
	Route::get('/product/kategori/{category_slug_url}', 'ProductController@filterProductByCategories')->name('user.product.category');
	Route::get('/product/kategori/{category_slug_url}/{subcategory_slug_url}', 'ProductController@filterProductBySubcategories')->name('user.product.subcategory');
	Route::get('/product/{m02_product_slug_url}', 'HomepageController@showProductDetail')->name('user.product.detail');
	Route::post('/product/search/', 'HomepageController@searchProduct')->name('search.product');
	Route::get('/search/product/', 'HomepageController@searchIndex')->name('search.product.view');
	Route::post('/product/{m02_product_id}/review', 'ProductController@addReview')->name('user.product.review');
	Route::post('/product/review/{m01_review_id}/update', 'ProductController@updateReview')->name('user.product.review.update');
	Route::delete('/product/review/{m01_review_id}/delete', 'ProductController@deleteReview')->name('user.product.review.delete');
	Route::post('/product/add/cart', 'ProductController@addToCart')->name('user.product.cart');
	Route::get('/product/buy/{m02_product_slug_url}', 'HomepageController@buyProduct')->name('user.product.buy');

	//Cart
	Route::get('/cart', 'HomepageController@cart')->name('user.cart.index');
	Route::post('/cart/update', 'ProductController@updateCart')->name('user.cart.update');
	Route::delete('/cart/{m01_cart}/delete', 'ProductController@deleteCart')->name('user.cart.delete');
	Route::get('/cart/count', 'ProductController@getCartCount')->name('user.cart.count');
	Route::get('/cart/checkout', 'HomepageController@checkout')->name('user.cart.checkout');
	Route::post('/cart/checkout', 'HomepageController@submitCheckout')->name('user.cart.checkout.save');

	//Order
	Route::get('/order', 'HomepageController@order')->name('user.order.index');
	Route::get('/order/{m01_order_id}', 'HomepageController@orderDetail')->name('user.order.detail');
	Route::get('/order/{m01_order_id}/payment', 'HomepageController@payment')->name('user.order.payment.index');
	Route::post('/order/{m01_order_id}/payment', 'HomepageController@submitPayment')->name('user.order.payment.save');
	Route::post('/shipping-cost', 'HomepageController@getShippingCost')->name('user.shipping.price');

	//Login
	Route::get('/user/login','LoginController@showLoginForm')->name('user.login.form');
	Route::post('/user/login','LoginController@login')->name('user.login');
	Route::get('/feedback', 'HomepageController@feedback')->name('user.feedback.index');
	Route::post('/feedback/save', 'HomepageController@saveFeedback')->name('user.feedback.save');
	//Reset PW
	//Register
	Route::get('/user/register/email', 'RegisterController@showVerifyEmail')->name('user.verify.register.with.email');
	Route::get('/user/register','RegisterController@showRegistrationForm')->name('user.register.form');
	Route::post('/user/register','RegisterController@register')->name('user.register');
	Route::get('/user/register/{m01_user}', 'RegisterController@showVerifyForm')->name('user.verify.register.form');
	Route::post('/verify/register/{m01_user}', 'RegisterController@verifyGoogle2F')->name('user.verify.register.google2f');
	Route::post('/register/verify/email', 'RegisterController@verifyEmail')->name('user.verify.register.email.code');

	Route::group(['middleware' => 'auth'], function(){
		Route::get('/logout', 'LoginController@logout')->name('user.logout');
		Route::get('/profile', 'ChangePassword@edit')->name('user.change.profile');
		Route::post('/profile', 'ChangePassword@update')->name('user.password.save');
	});
});

//With namespace Auth
Route::group(['namespace' => 'Auth'], function() {
	Route::get('/user/reset/password','ForgotPasswordController@frontendIndex')->name('user.password.request.index');
	Route::get('/admin/register', 'RegisterController@showRegisterForm')->name('admin.register.form');
	Route::post('/admin/register', 'RegisterController@register')->name('admin.register');
	Route::get('/admin/register/{m01_user}', 'RegisterController@showVerifyForm')->name('admin.verify.register.form');
	Route::post('/admin/verify/register/{m01_user}', 'RegisterController@verifyGoogle2F')->name('admin.verify.register.google2f');
	Route::get('/admin/email', 'RegisterController@showVerifyEmail')->name('admin.verify.register.email');
	Route::post('/admin/email/register', 'RegisterController@verify')->name('admin.verify.register.email.code');
	Route::get('/admin/reset/email/{m01_user}', 'RegisterController@showResetEmail')->name('admin.verify.reset.email');
	Route::post('/admin/reset/email/verify/{m01_user}', 'RegisterController@verifyReset')->name('admin.verify.reset.email.code');


	Route::get('/admin/login', 'LoginController@showLoginForm')->name('admin.login.form');
	Route::post('/admin/login', 'LoginController@login')->name('admin.login');
	Route::get('/admin/password/reset', 'ForgotPasswordController@index')->name('admin.password.request.index');
	Route::get('/admin/logout', 'LoginController@logout')->name('admin.logout');

	Route::get('/admin/password/reset/{token}', 'ResetPasswordController@showResetForm')->name('admin.password.reset');
	Route::post('/admin/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
	Route::get('/admin/reset/google/{m01_user}', 'RegisterController@showVerifyResetForm')->name('admin.verify.password.google2f.form');
	Route::post('/admin/verify/reset/google/{m01_user}', 'RegisterController@verifyResetGoogle2F')->name('admin.verify.password.google2f');

	Route::post('/admin/password/reset', 'ResetPasswordController@reset');

	Route::get('/user/password/reset/{token}', 'ResetPasswordController@frontendResetForm')->name('user.password.reset');
	Route::get('/user/reset/google/{m01_user}', 'RegisterController@showVerifyResetForm')->name('user.verify.password.google2f.form');
	Route::post('/user/verify/reset/google/{m01_user}', 'RegisterController@verifyResetGoogle2F')->name('user.verify.password.google2f');
	Route::get('/user/reset/email/{m01_user}', 'RegisterController@showResetEmail')->name('user.verify.reset.email');
	Route::post('/user/reset/email/verify/{m01_user}', 'RegisterController@verifyReset')->name('user.verify.reset.email.code');


});
Route::group(['middleware' => ['auth']], function(){
	Route::get('/admin/login/{m01_user}', 'VerificationController@showVerifyForm')->name('admin.verify.login.form');
	Route::post('/admin/verify/login/{m01_user}', 'VerificationController@verifyGoogle2F')->name('admin.verify.login.google2f');
	Route::get('/admin/login/email/{m01_user}', 'VerificationController@showVerifyEmail')->name('admin.verify.login.email');
	Route::post('/admin/login/verify/email/{m01_user}', 'VerificationController@verify')->name('admin.verify.login.email.code');


});

//With Auth and namespace Backend
Route::group(['middleware' => ['auth','admin']], function(){

	Route::group(['prefix' => 'admin','namespace' => 'Backend'], function(){
		Route::get('/','HomeController@index')->name('admin.dashboards.index');

		Route::group(['prefix' => 'password'], function() {
			Route::get('/change', 'ChangePassword@edit')->name('admin.change.password');
			Route::post('/save', 'ChangePassword@update')->name('admin.password.save');
		});
		
		Route::group(['prefix' => 'categories'], function(){
			Route::get('/', 'OutletCategoryController@index')->name('admin.categories.index');

app/Models/M02Outlet.php
<?php

namespace App\Models;

use App\Helpers\FileHelper;
use App\Models\M01Feedback;
use App\Models\M01User;
use App\Models\M03OutletCategory;
use Illuminate\Database\Eloquent\Model;

class M02Outlet extends Model
{
	protected $table = "m02_outlets";

	protected $fillable = [
		'outlet_no','name','address','phone','blok','profile_pic','status'
	];

	protected $guarded = ['m01_user_id','m03_outlet_category_id'];

	public $timestamps = false;

	public static function rules($id = '') 
	{
		$rules = [
			'outlet_no' => 'unique:m02_outlets,outlet_no'.($id ? ','.$id : ''),
			'phone' => 'required',
		];
		return $rules;
	}

	public function m01_user() 
	{
		return $this->belongsTo(M01User::class);
	}

	public function m03_outlet_category()
	{
		return $this->belongsTo(M03OutletCategory::class);
	}

	public function m01_feedback() 
    {
        return $this->hasMany(M01Feedback::class);
    }

	public function getPictureAttribute(){
		return FileHelper::getUrl($this->profile_pic);
    }
}

app/Http/Controllers/Frontend/AboutUsController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Helpers\SessionHelper;
use App\Models\M01User;
use App\Models\M03AboutUs;
use Auth;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class AboutUsController extends Controller
{
    protected $view = 'frontend.vendor.about-us';
    protected $route = 'vendor.about-us';
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $aboutUs = M03AboutUs::where('m02_outlet_id',Auth::user()->m02_outlet->id)->first();
        return view($this->view.'.index')
        ->with('aboutUsList', 'selected')
        ->with('aboutUsClass', 'start active open')
        ->with('aboutUs',$aboutUs);
    }

    public function store(Request $request) {
        $this->validate($request, M03AboutUs::rules());
        try {

            DB::beginTransaction();
            $aboutUs = M03AboutUs::where('m02_outlet_id',Auth::user()->m02_outlet->id)->first();
            if(!$aboutUs) $aboutUs = new M03AboutUs();
            $aboutUs->m02_outlet_id = Auth::user()->m02_outlet->id;
            $aboutUs->content = $request->content;
            $aboutUs->created_at = Carbon::now()->format('Y-m-d H:i:s');
            if (!$aboutUs->save()) {
                return back()->withInput()->withErrors($aboutUs->errors());
            }

            DB::commit();
            SessionHelper::setMessage("Tentang Kami berhasil disimpan.");
            return redirect()->route($this->route.'.index');

        } catch (\Exception $e) {
            DB::rollBack();
            \Log::error($e);
            return back()->withInput()->withErrors($e);
        }
    }

}

app/Http/Controllers/Frontend/ChangePassword.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Helpers\Enums\UserRole;
use App\Helpers\SessionHelper;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class ChangePassword extends Controller
{
    public function edit()
    {
        if(Auth::user()->role == UserRole::CUSTOMER) {
            return view('frontend.auth.profile');
        }elseif(Auth::user()->role == UserRole::VENDOR) {
            return view('frontend.auth.vendor_profile');
        }
    }

    public function update(Request $request)
    {
        $this->validate($request, [
            'old_password' => 'required',
            'password' => 'required|min:6|confirmed',
            'password_confirmation' => 'required|min:6',
        ]
    );

        $user = $request->user();
        if (!Hash::check($request->old_password, $user->password))
            return back()->withErrors(['old_password' => 'Incorect old password. Please enter the correct password']);
            $user->password = bcrypt($request->password);
            if ($request->googleotp) {
                $user->auth_option = 1;
                $user->googleotp = 1;
                $user->emailotp = 0;
            } elseif ($request->emailotp) {
                $user->auth_option = 2;
                $user->emailotp = 1;
                $user->googleotp = 0;
            } else {
                $user->auth_option = 0;
                $user->emailotp = 0;
                $user->googleotp = 0;
            }
            $user->save();
            SessionHelper::setMessage('Change password succeed');
            if($user->role == UserRole::CUSTOMER) {
                return redirect()->route('user.change.profile');
            }elseif($user->role == UserRole::VENDOR) {
                return redirect()->route('vendor.change.password');
                
            }
        }
    }

app/Http/Controllers/Frontend/ContactUsController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Helpers\SessionHelper;
use App\Models\M01Feedback;
use App\Models\M01User;
use App\Models\M03ContactUs;
use Auth;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Yajra\Datatables\Facades\Datatables;

class ContactUsController extends Controller
{
    protected $view = 'frontend.vendor.contact-us';
    protected $route = 'vendor.contact-us';
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $messages = M03ContactUs::where('m02_outlet_id',Auth::user()->m02_outlet->id)->get();
        return view($this->view.'.index')
        ->with('contactUsList', 'selected')
        ->with('contactUsClass', 'start active open')
        ->with('messages',$messages);
    }

    public function sendMessage(Request $request) {
        $data = array('name' => Auth::user()->name, 'content' => $request->content,'email' => $request->email);
        Mail::send('backend.mail.feedback', $data, function ($message) use ($data)
        {
            $emailCustomer = $data['email'];
            $message->from('nongsa.dev@gmail.com')->subject('Message Reply');
            $message->to($emailCustomer);
        });
        $feedback = M03ContactUs::where('id','=', $request->id)->first();
        $feedback->status = 1;
        $feedback->save();
        
        SessionHelper::setMessage("Pesan berhasil dikirim.");
        return redirect()->route($this->route.'.index');

    }

}

app/Http/Controllers/Frontend/Controller.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Frontend/HomeController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('frontend.vendor.dashboard.index')
        ->with('vendorList', 'selected')
        ->with('vendorClass', 'start active open');
    }
}

resources/views/frontend/order/detail.blade.php
@extends('layouts.frontend.master')
@section('content')
<?php

use App\Helpers\Enums\OrderStatus;

?>
<!-- BEGIN #promotions -->
<div class="section-container bg-white">
	<!-- BEGIN container -->
	<div class="container">
		<!-- BEGIN section-title -->
		@include('includes.session_message')
		<h1 class="section-title clearfix">ORDER DETAIL<br>
		</h1>
		<br>
		<!-- END section-title -->
		<!-- BEGIN row -->
        <div class="row row-space-10">
            <table class="table table-striped table-hover fullTable">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <tr>
                        <td class="col-md-6">
                            No. Invoice :
                        </td>
                        <td class="col-md-6">
                            {{ $order->invoice_no }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Delivery Type :
                        </td>
                        <td>
                            {{ $order->m03_shipping_method->name }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Delivery Cost :
                        </td>
                        <td>
                            Rp {{ $order->m03_shipping_method->price }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Address :
                        </td>
                        <td>
                            {{ $order->address }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Grand Total :
                        </td>
                        <td>
                            Rp {{ round($order->grand_total,0) }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Status :
                        </td>
                        <td>
                         {{ OrderStatus::getString($order->status) }}
                     </td>
                 </tr>
                 <tr>
                    <td colspan="2">
                        Product List :
                    </td>
                </tr>
            </div>
            <div class="col-md-3"></div>
        </table>
        @foreach ($outletIdList as $key => $outletId)
        <label>Resi No : {{ $resiNoList[$key] }}</label>
        <table class="table table-cart">
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th class="text-center">Price</th>
                    <th class="text-center">Quantity</th>
                    <th class="text-center">Total</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($orderList[$key] as $orderItem)
                <tr>
                    <td class="cart-product">
                        <div class="product-img">
                            <img src="{{ $orderItem->m02_product->picture }}" alt>
                        </div>
                        <div class="product-info">
                            <div class="title">{{ $orderItem->m02_product->name }}</div>
                            <div class="desc">{{ $orderItem->m02_product->description }}</div>
                        </div>
                    </td>
                    <td class="cart-price text-center">
                        {{ round($orderItem->price,0) }}
                    </td>
                    <td class="cart-price text-center">
                        {{ $orderItem->qty }}
                    </td>
                    <td class="cart-total text-center" >
                        {{ round($orderItem->subtotal,0) }}
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @endforeach
        @if ($order->status == 0) 
        <a href="{{ route('user.order.payment.index', $order->id) }}" type="submit" class="btn btn-info btn-outline float-right">Konfirmasi Pembayaran</a>
        @endif
    </div>
    <!-- END row -->
</div>
<!-- END container -->
</div>

@endsection

resources/views/frontend/order/index.blade.php
@extends('layouts.frontend.master')
@section('content')
<?php

use App\Helpers\Enums\OrderStatus;

?>
<!-- BEGIN #promotions -->
<div class="section-container bg-white">
	<!-- BEGIN container -->
	<div class="container">
		<!-- BEGIN section-title -->
		@include('includes.session_message')
		<h1 class="section-title clearfix">Order History<br>
		</h1>
		<br>
		<!-- END section-title -->
		<!-- BEGIN row -->
		<div class="row row-space-10">
            <div class="table-responsive">
                <table class="table table-striped table-hover fullTable">
                  <div class="col-md-3"></div>
                  <div class="col-md-6">
                    <tr>
                        <td class="col-md-3">No. Invoice</td>
                        <td class="col-md-3">Tanggal</td>
                        <td class="col-md-3">Total</td>
                        <td class="col-md-2">Status</td>
                        <td class="col-md-1">Action</td>

                    </tr>
                    @if ($orders)
                    @foreach ($orders as $order)
                    <tr>
                     <td class="col-md-3">{{ $order->invoice_no }}</td>
                     <td class="col-md-3">{{ $order->created_at }}</td>
                     <td class="col-md-3">Rp {{ round($order->grand_total) }}</td>
                     <td class="col-md-3">
                       {{ OrderStatus::getString($order->status) }}
                   </td>
                   <td>
                       <a href="{{ route('user.order.detail', $order->id) }}" class="btn btn-info btn-outline btn-sm">
                         <span class="fa fa-eye"></span> Lihat Detail
                     </a>
                 </td>
             </tr>
             @endforeach
             @endif
         </div>
         <div class="col-md-3"></div>
     </table>
 </div>
</div>
<!-- END row -->
</div>
<!-- END container -->
</div>
<!-- END #promotions -->
@endsection

resources/views/frontend/order/payment.blade.php
@extends('layouts.frontend.master')
@section('content')
<!-- BEGIN #promotions -->
<div class="section-container bg-white">
    <!-- BEGIN container -->
    <div class="container">
        <!-- BEGIN section-title -->
        @include('includes.session_message')
        <h1 class="section-title clearfix">Payment<br>
        </h1>
        <br>
        <!-- END section-title -->
        <!-- BEGIN row -->
        <div class="row row-space-10">
            <form class="form-horizontal" method="POST" action="{{ route('user.order.payment.save', $order->id) }}">
                {{ csrf_field() }}
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <div class="form-group m-b-15">
                        <input type="text" id="payment_date" class="form-control dateonlypicker" name="payment_date" placeholder="Select Date" required>
                    </div>
                    <div class="form-group m-b-15 {{ $errors->has('email') ? ' has-error' : '' }}">
                        <input type="number" id="amount" class="form-control" name="amount" placeholder="Type amount of payment" required>
                    </div>
                    <div class="form-group m-b-15">
                        Upload Proof of Payment
                    </div>
                    <div class="form-group m-b-15">
                        <img src="{{ asset('assets/img/noimage.png') }}" style="width: 210px; height: 210px" id="previewImage">
                        <input type="file" name="picture" id="imageSelect" class="form-control no-border">
                    </div>
                    <div class="login-buttons form-group">
                        <button type="submit" class="btn btn-success btn-block btn-lg">Submit</button>
                    </div>
               </div>
               <div class="col-md-4"></div>
           </form>
       </div>
        <!-- END row -->
    </div>
    <!-- END container -->
</div>
<!-- END #promotions -->
@endsection

@push('pageRelatedJs')
<script type="text/javascript">
    $(document).ready(function(){

        function readURL(input) {
            console.log('Read URL');
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    console.log(e);
                    $('#previewImage').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#imageSelect").change(function(){
            console.log('Change!');
            readURL(this);
        });
    });
</script>
@endpush